services:
  web:
    container_name: arileasing_emlak_backend
    build: .
    restart: unless-stopped
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/app/data
      - ./staticfiles:/app/staticfiles
    networks:
      - arileasing_network

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs/:/etc/ssl:ro
      #- staticfiles:/app/staticfiles:ro
      - ./staticfiles:/staticfiles
      - ./media:/media
    networks:
      - arileasing_network

# volumes:
#   staticfiles:

networks:
  arileasing_network:
    external: true