# Generated by Django 6.0.7 on 2026-08-18 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('event_type', models.CharField(blank=True, choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout')], max_length=25, null=True, verbose_name='Event Type')),
                ('username_attempted', models.CharField(blank=True, max_length=140, null=True, verbose_name='Username Attempt')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('failure_reason', models.CharField(blank=True, choices=[('bad_credentials', 'Hatalı kullanıcı adı/şifre'), ('inactive', 'Pasif kullanıcı'), ('locked', 'Hesap kilitli'), ('other', 'Diğer')], max_length=25, null=True, verbose_name='Failure Reason')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_auth_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
