# Generated by Django 6.0.7 on 2026-09-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_admin_user_is_yetkili'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_approval_sms',
            field=models.BooleanField(default=False, help_text='İşaretleyip "Onaylı" ile birlikte kaydedince kullanıcıya "Üyeliğiniz onaylandı" SMS\'i gider. Kaydedildikten sonra işaret otomatik kalkar.', verbose_name="Onay SMS'i Gönder"),
        ),
    ]
