# Generated by Django 6.0.7 on 2026-08-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
